export const projects = [
  {
    title: 'ShareMe',
    description: "A social media application where users can share images with on a feed page and can also download and save other's images",
    image: '/images/9.png',
    tags: ['Sanity', 'UUID',  'Masonry Layout', 'React Icons'],
    source: 'https://github.com/swastik58/share_me',
    visit: 'https://shareme-swastik.netlify.app/',
    id: 0,
  },
  {
    title: 'Explorix',
    description: "A frontend design of a tourism website containing information to some places in the world and containing different links to redirect to their official tourism websites. The site also contains a 404 page and a sorry page.",
    image: '/images/5.png',
    tags: ['Gatsby', 'GraphQL',  'Styled Components', 'Pexels'],
    source: 'https://github.com/swastik58/explorix',
    visit: 'https://explorix-tourism.netlify.app/',
    id: 1,
  },
  {
    title: 'Blogger',
    description: 'A blog website where anyone can upload their blogs using graph cms and others can view and also comment on their blogs only if the user allows the comments to be visible. The blog posts are arranged in the descending order of creation and blogs can also be found at their specific categories',
    image: '/images/8.png',
    tags: ['NextJS', 'GraphQL', 'Graph CMS','Tailwind CSS'],
    source: 'https://github.com/swastik58/blogger',
    visit: 'https://blogger-three.vercel.app/',
    id: 2,
  },
  {
    title: 'Amazon 2.0',
    description: 'The frontend clone for the amazon website. Login here using your google credentials and then add items to your cart. The checkout functionality is also made possible using Stripe. Therefore, you can enter trial card details to complete the payment',
    image: '/images/6.png',
    tags: ['NextJS', 'TailwindCSS', 'Firebase', 'NextAuth', 'Stripe'],
    source: 'https://github.com/swastik58/amazon-clone',
    visit: 'https://amazon-2-clone.netlify.app/',
    id: 3,
  },
  {
    title: 'Cryptoverse',
    description: "This is a web app where the user can find the condition of sky anywhere in the world. The queries needed to be entered by the user are the name of city and country.",
    image: '/images/7.png',
    tags: ['React', 'Bootstrap', 'Github Weather icons', 'Axios'],
    source: 'https://github.com/swastik58/cryptoverse',
    visit: 'https://cryptoverse-swastik.netlify.app/',
    id: 4,
  },
  {
    title: 'One Stop Entertainment',
    description: "An app to get details about all the latest movies and TV-series from all around the world. From the trending page you can also get to know about the latest releases and also watch their trailers. You can also check the IMDB ratings of these shows.",
    image: '/images/1.png',
    tags: ['Axios', 'The Movie Database API', 'React', 'Material-UI'],
    source: 'https://github.com/swastik58/movie-series',
    visit: 'https://one-stop-entertainment.netlify.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Passed Class 10 from CBSE with a CGPA of 10.0', },
  { year: 2018, text: 'Passed Class 12 from CBSE with a Percentage of 90.2', },
  { year: 2018, text: 'Started college at Heritage Institute of Technology', },
  { year: 2020, text: 'Started learning Web Developement also ReactJS along with it', },
  { year: 2021, text: 'Still continuing Web Developement by taking help from YouTube and other websites', },
];
